# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3df44aff2f2be3d96f531c0ad5441ba765dfd0681fbcc7f39f0482b07ac2def2241b07345e53e44b262e2f6bcf2a9fc040186f8c4736bf6beba91a5ab382b0d7

test:
  secret_key_base: ecfd00dcf136fb0ebbb77402ae44c5869f5cf0e6664dfcccb210222ac7dc57aa4c5d1cd3ab13e109edf1ef403f2c6cb3999c28b3fdf729cd34ebe1d4d55137f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
